CREATE DATABASE bdmvc;
USE DATABASE bdmvc;
CREATE TABLE t_usuario(
	USU_ID INT PRIMARY KEY AUTO_INCREMENT,
	USU_UID VARCHAR(10),
	USU_NOMBRES VARCHAR(20) NOT NULL,
	USU_APELLIDOS VARCHAR(20) NOT NULL,
	USU_EMAIL VARCHAR(20) NOT NULL,
	USU_PASSWORD VARCHAR(100) NOT NULL,
	USU_TELEFONO VARCHAR(10) NOT NULL,
	USU_FCH_NAC DATE
	USU_ROL CHAR(1) NOT NULL,
);

CREATE TABLE t_programa (
	PRO_ID INT PRIMARY KEY AUTO_INCREMENT,
	PRO_UID VARCHAR(10),
	PRO_NOMBRE VARCHAR(30) NOT NULL,
	PRO_CODIGO VARCHAR(20) NOT NULL
);

CREATE TABLE t_us_pro(
	USPRO_ID INT PRIMARY KEY AUTO_INCREMENT,
	USPRO_UID VARCHAR(10),
	USPRO_USU_ID INT,
	USPRO_PRO_ID INT,
	USPRO_FCH_INS DATE,
	FOREIGN KEY (USPRO_USU_ID) REFERENCES t_usuario(USU_ID),
	FOREIGN KEY (USPRO_PRO_ID) REFERENCES t_programa(PRO_ID)
)